config/routes.rb
Rails.application.routes.draw do
  
  resources :dummies
  namespace :api do
    namespace :v1 do
      resources :fruits 
    end
  end
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dummy.rb
class Dummy < ApplicationRecord
end

app/models/fruit.rb
class Fruit < ApplicationRecord
end

app/controllers/api/v1/fruits_controller.rb
class Api::V1::FruitsController < ApplicationController
  before_action :set_fruit, only: %i[ show edit update destroy ]

  # GET /fruits or /fruits.json
  def index
    @fruits = Fruit.all
    render json: @fruits
  end

  # GET /fruits/1 or /fruits/1.json
  def show
  end

  # GET /fruits/new
  def new
    @fruit = Fruit.new
  end

  # GET /fruits/1/edit
  def edit
  end

  # POST /fruits or /fruits.json
  def create
    @fruit = Fruit.new(fruit_params)

    respond_to do |format|
      if @fruit.save
        # format.html { redirect_to @fruit, notice: "Fruit was successfully created." }
        format.json { render :show, status: :created, location: @fruit }
      else
        # format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fruit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fruits/1 or /fruits/1.json
  def update
    @fruit = Fruit.find(params[:id])
    render json: @fruit
  end

  # DELETE /fruits/1 or /fruits/1.json
  def destroy
    @fruit.destroy
    respond_to do |format|
      # format.html { redirect_to fruits_url, notice: "Fruit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fruit
      @fruit = Fruit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fruit_params
      params.require(:fruit).permit(:id, :name, :desc)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/dummies_controller.rb
class DummiesController < ApplicationController
  before_action :set_dummy, only: %i[ show edit update destroy ]

  # GET /dummies or /dummies.json
  def index
    @dummies = Dummy.all
  end

  # GET /dummies/1 or /dummies/1.json
  def show
  end

  # GET /dummies/new
  def new
    @dummy = Dummy.new
  end

  # GET /dummies/1/edit
  def edit
  end

  # POST /dummies or /dummies.json
  def create
    @dummy = Dummy.new(dummy_params)

    respond_to do |format|
      if @dummy.save
        format.html { redirect_to @dummy, notice: "Dummy was successfully created." }
        format.json { render :show, status: :created, location: @dummy }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dummy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dummies/1 or /dummies/1.json
  def update
    respond_to do |format|
      if @dummy.update(dummy_params)
        format.html { redirect_to @dummy, notice: "Dummy was successfully updated." }
        format.json { render :show, status: :ok, location: @dummy }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dummy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dummies/1 or /dummies/1.json
  def destroy
    @dummy.destroy
    respond_to do |format|
      format.html { redirect_to dummies_url, notice: "Dummy was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dummy
      @dummy = Dummy.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dummy_params
      params.require(:dummy).permit(:name, :text)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dummies_helper.rb
module DummiesHelper
end

app/helpers/fruits_helper.rb
module FruitsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/dummies/_form.html.erb
<%= form_with(model: dummy) do |form| %>
  <% if dummy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dummy.errors.count, "error") %> prohibited this dummy from being saved:</h2>

      <ul>
        <% dummy.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dummies/edit.html.erb
<h1>Editing Dummy</h1>

<%= render 'form', dummy: @dummy %>

<%= link_to 'Show', @dummy %> |
<%= link_to 'Back', dummies_path %>

app/views/dummies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dummies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dummies.each do |dummy| %>
      <tr>
        <td><%= dummy.name %></td>
        <td><%= dummy.text %></td>
        <td><%= link_to 'Show', dummy %></td>
        <td><%= link_to 'Edit', edit_dummy_path(dummy) %></td>
        <td><%= link_to 'Destroy', dummy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dummy', new_dummy_path %>

app/views/dummies/new.html.erb
<h1>New Dummy</h1>

<%= render 'form', dummy: @dummy %>

<%= link_to 'Back', dummies_path %>

app/views/dummies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dummy.name %>
</p>

<p>
  <strong>Text:</strong>
  <%= @dummy.text %>
</p>

<%= link_to 'Edit', edit_dummy_path(@dummy) %> |
<%= link_to 'Back', dummies_path %>

app/views/fruits/_form.html.erb
<%= form_with(model: fruit) do |form| %>
  <% if fruit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fruit.errors.count, "error") %> prohibited this fruit from being saved:</h2>

      <ul>
        <% fruit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_field :desc %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fruits/edit.html.erb
<h1>Editing Fruit</h1>

<%= render 'form', fruit: @fruit %>

<%= link_to 'Show', @fruit %> |
<%= link_to 'Back', fruits_path %>

app/views/fruits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fruits</h1>

<div class="flex flex-col">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Name
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Description
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider" colspan="3"></th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            <% @fruits.each do |fruit| %>
              <tr>
                <td class="px-6 py-4 whitespace-nowrap">
                  <div class="text-sm font-medium text-gray-900"><%= fruit.name %></div>
                </td>
                <td class="px-6 py-4 whitespace-nowrap">
                  <div class="text-sm font-medium text-gray-900"><%= fruit.desc %></div>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                  <%= link_to 'Show', fruit, class="text-indigo-600 hover:text-indigo-900" %>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                  <%= link_to 'Edit', edit_fruit_path(fruit), class="text-indigo-600 hover:text-indigo-900" %>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                  <%= link_to 'Destroy', fruit, method: :delete, data: { confirm: 'Are you sure?' }, class="text-indigo-600 hover:text-indigo-900" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<%= link_to 'New Fruit', new_fruit_path %>

app/views/fruits/new.html.erb
<h1>New Fruit</h1>

<%= render 'form', fruit: @fruit %>

<%= link_to 'Back', fruits_path %>

app/views/fruits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @fruit.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @fruit.desc %>
</p>

<%= link_to 'Edit', edit_fruit_path(@fruit) %> |
<%= link_to 'Back', fruits_path %>

app/views/home/index.html.erb
<%= react_component 'Main' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestReact</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body class="bg-gray-800 font-sans leading-normal tracking-normal mt-12">
    <div class="ui fixed inverted menu">
      <div class="ui container">
        <a href="#" class="header item">Test App</a>
        <a href="#" class="item">Home</a>
        <a href="#" class="item">Fruits</a>
        <div class="ui simple dropdown item">
          Dropdown <i class="dropdown icon"></i>
          <div class="menu">
            <a class="item" href="#">Link Item</a>
            <a class="item" href="#">Link Item</a>
            <div class="divider"></div>
            <div class="header">Header Item</div>
            <div class="item">
              <i class="dropdown icon"></i>
              Sub Menu
              <div class="menu">
                <a class="item" href="#">Link Item</a>
                <a class="item" href="#">Link Item</a>
              </div>
            </div>
            <a class="item" href="#">Link Item</a>
          </div>
        </div>
      </div>
    </div>
    <div class="ui main text container">
      <%= yield %>
    </div>
  </body>
</html>